version: '3.8'

services:
  redis:
    image: 'redis:latest'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  proxy:
    build: .
    ports:
      - '80:80'
    environment:
      DEBUG: 1
      PORT: 80
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./:/app/:ro

    healthcheck:
      #test: "exit 0"
      test:  wget --no-verbose --tries=1 --spider http://localhost/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s